{% set name = "openstacksdk" %}
{% set version = "0.17.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "8de5ca34ccfab804ef6d806102ff61542bc5a6d58c72edf10c2066668e85c843" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - pyyaml >=3.12
    - appdirs >=1.3.0
    - requestsexceptions >=1.2.0
    - jsonpatch !=1.20,>=1.16
    - six >=1.10.0
    - os-service-types >=1.2.0
    - keystoneauth1 >=3.8.0
    - deprecation >=1.0
    - munch >=2.1.0
    - decorator >=3.4.0
    - jmespath >=0.9.0
    - ipaddress >=1.0.17  # [py2k]
    - futures >=3.0.0  # [py2k]
    - iso8601 >=0.1.11
    - netifaces >=0.10.4
    - dogpile.cache >=0.6.2
    - cryptography >=2.1

test:
  imports:
    - openstack

about:
  home: https://developer.openstack.org/sdks/python/openstacksdk/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Collection of libraries for building applications to work with OpenStack clouds.
  doc_url: https://developer.openstack.org/sdks/python/openstacksdk/
  dev_url: https://github.com/openstack/python-openstacksdk

extra:
  recipe-maintainers:
    - pmlandwehr
