{% set name = "openstacksdk" %}
{% set version = "4.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/6c/e7/4921e513dc00e2b052b196e4a7055351b74192a680470ab287b2332b0c6a/openstacksdk-{{ version }}.tar.gz
  sha256: 23348aa69c6cc6c1ed0e8f03fb42b156519ed8cfcd143e783ef5c1dd800ad9f1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openstack-inventory = openstack.cloud.cmd.inventory:main
  noarch: python


requirements:
  host:
    - python {{ python_min }}
    - pip
    - pbr !=2.1.0,>=2.0.0
    - setuptools

  run:
    - python >={{ python_min }}
    - pbr !=2.1.0,>=2.0.0
    - pyyaml >=3.13
    - appdirs >=1.3.0
    - requestsexceptions >=1.2.0
    - jsonpatch !=1.20,>=1.16
    - os-service-types >=1.7.0
    - keystoneauth1 >=3.18.0
    - decorator >=4.4.1
    - jmespath >=0.9.0
    - iso8601 >=0.1.11
    - psutil >=3.2.2
    - dogpile.cache >=0.6.5
    - cryptography >=2.7
    - platformdirs >=3

test:
  requires:
    - python {{ python_min }}
  imports:
    - openstack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://developer.openstack.org/sdks/python/openstacksdk/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Collection of libraries for building applications to work with OpenStack clouds.
  doc_url: https://developer.openstack.org/sdks/python/openstacksdk/
  dev_url: https://github.com/openstack/python-openstacksdk

extra:
  recipe-maintainers:
    - pmlandwehr
    - tschoonj
