{% set name = "openstacksdk" %}
{% set version = "0.10.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "44f40b45bc2ac481c737303ed8e31d71a03eb2e8245d7baf72cfc1fdfe8d3ce5" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - pyyaml >=3.10
    - appdirs >=1.3.0
    - requestsexceptions >=1.2.0
    - jsonpatch !=1.20,>=1.16
    - six >=1.10.0
    - os-service-types >=1.1.0
    - keystoneauth1 >=3.3.0
    - deprecation >=1.0
    - munch >=2.1.0
    - decorator >=3.4.0
    - jmespath >=0.9.0
    - ipaddress >=1.0.16  # [py<33]
    - futures >=3.0.0  # [py2k]
    - iso8601 >=0.1.11
    - netifaces >=0.10.4
    - dogpile.cache >=0.6.2

test:
  imports:
    - openstack

about:
  home: https://developer.openstack.org/sdks/python/openstacksdk/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Collection of libraries for building applications to work with OpenStack clouds.
  doc_url: https://developer.openstack.org/sdks/python/openstacksdk/
  dev_url: https://github.com/openstack/python-openstacksdk

extra:
  recipe-maintainers:
    - pmlandwehr
