{% set name = "openstacksdk" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccac9b158e3d36b959a3bdce71bd4f883d7758fef6856841c855ff2b22c941ea

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openstack-inventory = openstack.cloud.cmd.inventory:main
  noarch: python


requirements:
  host:
    - python {{ python_min }}
    - pip
    - pbr !=2.1.0,>=2.0.0
    - setuptools

  run:
    - python >={{ python_min }}
    - pbr !=2.1.0,>=2.0.0
    - pyyaml >=3.13
    - appdirs >=1.3.0
    - requestsexceptions >=1.2.0
    - jsonpatch !=1.20,>=1.16
    - os-service-types >=1.7.0
    - keystoneauth1 >=3.18.0
    - decorator >=4.4.1
    - jmespath >=0.9.0
    - iso8601 >=0.1.11
    - netifaces >=0.10.4
    - dogpile.cache >=0.6.5
    - cryptography >=2.7
    - platformdirs >=3

test:
  requires:
    - python {{ python_min }}
  imports:
    - openstack

about:
  home: https://developer.openstack.org/sdks/python/openstacksdk/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Collection of libraries for building applications to work with OpenStack clouds.
  doc_url: https://developer.openstack.org/sdks/python/openstacksdk/
  dev_url: https://github.com/openstack/python-openstacksdk

extra:
  recipe-maintainers:
    - pmlandwehr
    - tschoonj
