{% set name = "openstacksdk" %}
{% set version = "0.54.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73a3be3407d524cf75ba615bd4fe60d067ed7ac1628c6561cad58bcc2850f1f7
  patches:
    # remove when next version is released!
    - 0fb65458d27ca6d5aba084181f730f23a8cb64ae.diff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openstack-inventory = openstack.cloud.cmd.inventory:main
  skip: true  # [py<36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - pyyaml >=3.13
    - appdirs >=1.3.0
    - requestsexceptions >=1.2.0
    - jsonpatch !=1.20,>=1.16
    - os-service-types >=1.7.0
    - keystoneauth1 >=3.18.0
    - munch >=2.1.0
    - decorator >=4.4.1
    - jmespath >=0.9.0
    - iso8601 >=0.1.11
    - netifaces >=0.10.4
    - dogpile.cache >=0.6.5
    - cryptography >=2.7
    - importlib_metadata >=1.7.0  # [py<38]

test:
  imports:
    - openstack

about:
  home: https://developer.openstack.org/sdks/python/openstacksdk/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Collection of libraries for building applications to work with OpenStack clouds.
  doc_url: https://developer.openstack.org/sdks/python/openstacksdk/
  dev_url: https://github.com/openstack/python-openstacksdk

extra:
  recipe-maintainers:
    - pmlandwehr
    - tschoonj
