appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YBfQ+hA0PZkq9qb0bFR/ou6WJ80Gfb9bjqTF+erI0FYaZSShlfFEdsXWMKO+Bw6R1VNbFUUTnrbMGruQkA/Qu6xiwc0fJd5wQE/KBmSS1HLI56TTUikQ2/i7pdQTPUZPB0YOLBy0MakObnzhGCVynl9L75mIKqEDEVY6o3EmM7cwWDGpmp86JxfClIoUOcVfo7/bX51xSaiIX72ksQE/stxqoBHiXO7QXAGmP6gY0HAwtvgj8tSotu/M/qQor1XGkrIV0wJcuiassA0v1JYOSZummdUheJHLzYK+oDFbDfob8yeyGNR158OjO887r6fH14dYd6UkuyFccqivps0L+YDfF9MXSrTNKorJDbIRtNykUnS+5NBNiG92W/UDt9PqPuRsUjeCQlB13HMxAvDfu7UVH+2IXZiEcsLlmvZqt2VSlS1SJdGxM+LAyz5EcjF5m1PFWE38j8P7z7VBjJiRhjl1lpN/UF8/JpONSL8G835r6hdNHCQRTc1NkrToNdOnoVEIQ2ltwM0xVgEdIYwVY1UaVu68PxPdvwU+8k7ZSSJcEx+fPPnHoQkAXAiii/SldOsUP26lVpPYvzRpcL0jc0apfgY7fDxUTN5Iufc14G5ECZPcm+UPW4O3VSk0U0Niask2SzYYDlvAecQhakH6TAShL1tvNYswqdtA8cP1Mu4=}
